services:
  api:
    build: .
    container_name: api

    restart: unless-stopped

    ports:
      - "8500:8500"

    env_file:
      - .env

    volumes:
      - /home/ec2-user/.aws:/root/.aws:ro

    networks:
      - creminox-network

networks:
  creminox-network:
    external: true